"use client"

import { useEffect, useState } from "react"

/**
 * Dynamically loads the wasm module generated by wasm-pack.
 * Returns the module once ready or null while loading.
 */
export function useWASM() {
  const [wasmModule, setWasmModule] = useState<any | null>(null)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    let isMounted = true

    import("../public/wasm/multilayer_perceptron.js")
      .then(async (module) => {
        // Initialize the WASM module
        await module.default()
        if (isMounted) {
          setWasmModule(module)
          setError(null)
        }
      })
      .catch((err) => {
        console.error("Failed to load WASM module", err)
        if (isMounted) {
          setError("Failed to load WASM module")
        }
      })

    return () => {
      isMounted = false
    }
  }, [])

  return { wasmModule, wasmError: error }
}
